baseURL: 'https://mejoreslectores.com'
title: MEJORES LECTORES
theme: cupper-hugo-theme
googleAnalytics: 'G-DGH72DH8MG'
languageCode: es-co
defaultContentLanguage: es
defaultContentLanguageInSubdir: false
enableGitInfo: true
removePathAccents: true
pluralizeListTitles: false
summaryLength: 35
enableInlineShortcodes: true

menu:
  nav:
    - name: Curso
      url: /curso/
      weight: 1

taxonomies:
  tag: tags
permalinks:
  list: '/:filename/'
  # curso: '/:filename/'
related:
  includeNewer: true
  threshold: 70
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: date
      weight: 50
imaging:
  quality: 85
  
params:
  redirigirHome: 'curso/01-introduccion/'
  description: Taller Experimental de Comprensión Lectora.
  homeMetaContent: Taller Experimental de Comprensión Lectora.
  footer: ""
  footer2: "© Andrés Peña y Jeysson Martín, 2022.<br>MAESTRÍA EN DISEÑO Y GESTIÓN DE ESCENARIOS VIRTUALES DE APRENDIZAJE.<BR> UNIVERSIDAD DE LA SALLE."
  dateFormat: 'Jan 2, 2006'
  author: Andrés Eduardo Peña
  images:
    - images/site-feature-image.jpg
  katex: false
  darkThemeAsDefault: false
  headingLinks: false
  showThemeSwitcher: false
  moveFooterToHeader: false
  search: false
  facebook: Lectupedia
  twitter: andreseduardop_
  linkedin: andreseduardop

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  tableOfContents:
    startLevel: 2
    endLevel: 2
    ordered: true
